# DEVELOPMENT ADDRESS
baseURL = "https://cdesg-development.netlify.com/"

# PRODUCTION ADDRESS
#baseURL = "TO DO"

# DISABLE HUGO FROM GENERATING THE FOLLOWING
disableKinds = ["RSS", "taxonomy", "taxonomyTerm", "sitemap"]

# LANGUAGE CODE
languageCode = "en-ca"

# BUILD THEME
# No theme was used - everything is in root layout folder
# theme = ""

# SITE SETTINGS
title = "Canadian Development Economic Study Group"

# USER DEFINED SITE PARAMETERS
[params]
  description = "To do"
